### ISSUE TITLE
OSError: no file with expected extension

### ISSUE THREAD

**Issue by jlillo** [mzechmeister/ke#2]
I am trying to install this package in a macOS (Sierra) to use it with Python2.7. I simply downloaded the python folder I tried to import ke as:

> import ke

But I get the following error:

OSError                                   Traceback (most recent call last)
<ipython-input-1-9ea02d1c9fa0> in <module>()
----> 1 import ke

/Users/lillo_box/anaconda/lib/python2.7/site-packages/ke.py in <module>()
      6 ptr_double = np.ctypeslib.ndpointer(dtype=np.float)
      7
----> 8 _ke = np.ctypeslib.load_library('lib/ke', '.')
      9 "%x"%ctypes.addressof(_ke._E)
     10 _ke_newton = np.ctypeslib.load_library('lib/ke_newton', '.')

/Users/lillo_box/anaconda/lib/python2.7/site-packages/numpy/ctypeslib.pyc in load_library(libname, loader_path)
    155                     raise
    156         ## if no successful return in the libname_ext loop:
--> 157         raise OSError("no file with expected extension")
    158
    159     ctypes_load_library = deprecate(load_library, 'ctypes_load_library',

OSError: no file with expected extension

Any help is very welcome!
Thanks,
Jorge

**Comment by mzechmeister** [comment]
Hi Jorge,

The `lib/*.c` must be compiled. The commands are in the header of the files. But now I have also updated the [ReadMe](../blob/master/python/README.md) and created a [setup.py](../blob/6d903a027ce62b66b4e02c3e8e89316aecf9e961/python/setup.py).

Still the issue occurs, when your are not in the parent directory. The relative import
https://github.com/mzechmeister/ke/blob/ab4db86ee2b3a8be2f0d0cffe3e0e4c700c8d233/python/ke.py#L8
is not properly recognised.

I will improve this.

Thanks,
Mathias

**Comment by mzechmeister** [comment]
The fix follows the suggestion from:
https://stackoverflow.com/questions/2980479/python-ctypes-loading-dll-from-from-a-relative-path
Seem like there isn't a more elegant solution for relative import with ctypes.
